In [1]:
!pip install -U pip setuptools==68.0.0 wheel

!pip install \
    numpy==1.24.3 \
    pandas==2.0.3 \
    pytorch_lightning==2.0.6 \
    scikit_learn==1.3.1 \
    torch==2.0.1 \
    tqdm==4.65.0 \
    transformers==4.33.3 \
    peft==0.5.0 \
    accelerate==0.23.0

!pip install microformer-mgm
!pip install optuna
!pip uninstall -y jax jaxlib

Requirement already satisfied: pip in /usr/local/lib/python3.11/dist-packages (26.2.1)
Requirement already satisfied: setuptools==68.0.0 in /usr/local/lib/python3.11/dist-packages (68.0.0)
Requirement already satisfied: wheel in /usr/local/lib/python3.11/dist-packages (0.48.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.11/dist-packages (from wheel) (24.2)
Requirement already satisfied: numpy==1.24.3 in /usr/local/lib/python3.11/dist-packages (1.24.3)
Requirement already satisfied: pandas==2.0.3 in /usr/local/lib/python3.11/dist-packages (2.0.3)
Requirement already satisfied: pytorch_lightning==2.0.6 in /usr/local/lib/python3.11/dist-packages (2.0.6)
Requirement already satisfied: scikit_learn==1.3.1 in /usr/local/lib/python3.11/dist-packages (1.3.1)
Requirement already satisfied: torch==2.0.1 in /usr/local/lib/python3.11/dist-packages (2.0.1)
Requirement already satisfied: tqdm==4.65.0 in /usr/local/lib/python3.11/dist-packages (4.65.0)
Requirement already satisfied: transformers==4.33.3 in /usr/local/lib/python3.11/dist-packages (4.33.3)
Requirement already satisfied: peft==0.5.0 in /usr/local/lib/python3.11/dist-packages (0.5.0)
Requirement already satisfied: accelerate==0.23.0 in /usr/local/lib/python3.11/dist-packages (0.23.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas==2.0.3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas==2.0.3) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.11/dist-packages (from pandas==2.0.3) (2025.2)
Requirement already satisfied: PyYAML>=5.4 in /usr/local/lib/python3.11/dist-packages (from pytorch_lightning==2.0.6) (6.0.2)
Requirement already satisfied: fsspec>2021.06.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>2021.06.0->pytorch_lightning==2.0.6) (2025.3.2)
Requirement already satisfied: torchmetrics>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from pytorch_lightning==2.0.6) (1.9.0)
Requirement already satisfied: packaging>=17.1 in /usr/local/lib/python3.11/dist-packages (from pytorch_lightning==2.0.6) (24.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from pytorch_lightning==2.0.6) (4.14.1)
Requirement already satisfied: lightning-utilities>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from pytorch_lightning==2.0.6) (0.15.3)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from scikit_learn==1.3.1) (1.15.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from scikit_learn==1.3.1) (1.5.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit_learn==1.3.1) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1) (3.18.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1) (1.13.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1) (11.7.99)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1) (11.7.99)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1) (11.7.101)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1) (8.5.0.96)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1) (11.10.3.66)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1) (10.2.10.91)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1) (11.4.0.1)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1) (11.7.4.91)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1) (2.14.3)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1) (11.7.91)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1) (2.0.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.15.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.33.3) (0.33.4)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.33.3) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers==4.33.3) (2.32.3)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.33.3) (0.13.3)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.33.3) (0.5.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from peft==0.5.0) (5.9.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch==2.0.1) (68.0.0)
Requirement already satisfied: wheel in /usr/local/lib/python3.11/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch==2.0.1) (0.48.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.11/dist-packages (from triton==2.0.0->torch==2.0.1) (3.31.6)
Requirement already satisfied: lit in /usr/local/lib/python3.11/dist-packages (from triton==2.0.0->torch==2.0.1) (23.1.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.15.1->transformers==4.33.3) (1.1.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>2021.06.0->pytorch_lightning==2.0.6) (3.11.15)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning==2.0.6) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning==2.0.6) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning==2.0.6) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning==2.0.6) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning==2.0.6) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning==2.0.6) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning==2.0.6) (1.20.1)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.11/dist-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning==2.0.6) (3.10)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas==2.0.3) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch==2.0.1) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.33.3) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.33.3) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.33.3) (2025.7.14)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy->torch==2.0.1) (1.3.0)
Requirement already satisfied: microformer-mgm in /usr/local/lib/python3.11/dist-packages (0.5.8)
Requirement already satisfied: numpy==1.24.3 in /usr/local/lib/python3.11/dist-packages (from microformer-mgm) (1.24.3)
Requirement already satisfied: pandas==2.0.3 in /usr/local/lib/python3.11/dist-packages (from microformer-mgm) (2.0.3)
Requirement already satisfied: pytorch-lightning==2.0.6 in /usr/local/lib/python3.11/dist-packages (from microformer-mgm) (2.0.6)
Requirement already satisfied: scikit-learn==1.3.1 in /usr/local/lib/python3.11/dist-packages (from microformer-mgm) (1.3.1)
Requirement already satisfied: setuptools==68.0.0 in /usr/local/lib/python3.11/dist-packages (from microformer-mgm) (68.0.0)
Requirement already satisfied: torch==2.0.1 in /usr/local/lib/python3.11/dist-packages (from microformer-mgm) (2.0.1)
Requirement already satisfied: tqdm==4.65.0 in /usr/local/lib/python3.11/dist-packages (from microformer-mgm) (4.65.0)
Requirement already satisfied: transformers==4.33.3 in /usr/local/lib/python3.11/dist-packages (from microformer-mgm) (4.33.3)
Requirement already satisfied: accelerate>=0.20.1 in /usr/local/lib/python3.11/dist-packages (from microformer-mgm) (0.23.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas==2.0.3->microformer-mgm) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas==2.0.3->microformer-mgm) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.11/dist-packages (from pandas==2.0.3->microformer-mgm) (2025.2)
Requirement already satisfied: PyYAML>=5.4 in /usr/local/lib/python3.11/dist-packages (from pytorch-lightning==2.0.6->microformer-mgm) (6.0.2)
Requirement already satisfied: fsspec>2021.06.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>2021.06.0->pytorch-lightning==2.0.6->microformer-mgm) (2025.3.2)
Requirement already satisfied: torchmetrics>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from pytorch-lightning==2.0.6->microformer-mgm) (1.9.0)
Requirement already satisfied: packaging>=17.1 in /usr/local/lib/python3.11/dist-packages (from pytorch-lightning==2.0.6->microformer-mgm) (24.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from pytorch-lightning==2.0.6->microformer-mgm) (4.14.1)
Requirement already satisfied: lightning-utilities>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from pytorch-lightning==2.0.6->microformer-mgm) (0.15.3)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.1->microformer-mgm) (1.15.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.1->microformer-mgm) (1.5.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.1->microformer-mgm) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1->microformer-mgm) (3.18.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1->microformer-mgm) (1.13.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1->microformer-mgm) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1->microformer-mgm) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1->microformer-mgm) (11.7.99)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1->microformer-mgm) (11.7.99)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1->microformer-mgm) (11.7.101)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1->microformer-mgm) (8.5.0.96)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1->microformer-mgm) (11.10.3.66)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1->microformer-mgm) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1->microformer-mgm) (10.2.10.91)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1->microformer-mgm) (11.4.0.1)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1->microformer-mgm) (11.7.4.91)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1->microformer-mgm) (2.14.3)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1->microformer-mgm) (11.7.91)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.11/dist-packages (from torch==2.0.1->microformer-mgm) (2.0.0)
Requirement already satisfied: wheel in /usr/local/lib/python3.11/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch==2.0.1->microformer-mgm) (0.48.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.15.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.33.3->microformer-mgm) (0.33.4)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.33.3->microformer-mgm) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers==4.33.3->microformer-mgm) (2.32.3)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.33.3->microformer-mgm) (0.13.3)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.33.3->microformer-mgm) (0.5.3)
Requirement already satisfied: cmake in /usr/local/lib/python3.11/dist-packages (from triton==2.0.0->torch==2.0.1->microformer-mgm) (3.31.6)
Requirement already satisfied: lit in /usr/local/lib/python3.11/dist-packages (from triton==2.0.0->torch==2.0.1->microformer-mgm) (23.1.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.15.1->transformers==4.33.3->microformer-mgm) (1.1.5)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from accelerate>=0.20.1->microformer-mgm) (5.9.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>2021.06.0->pytorch-lightning==2.0.6->microformer-mgm) (3.11.15)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning==2.0.6->microformer-mgm) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning==2.0.6->microformer-mgm) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning==2.0.6->microformer-mgm) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning==2.0.6->microformer-mgm) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning==2.0.6->microformer-mgm) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning==2.0.6->microformer-mgm) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning==2.0.6->microformer-mgm) (1.20.1)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.11/dist-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning==2.0.6->microformer-mgm) (3.10)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas==2.0.3->microformer-mgm) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch==2.0.1->microformer-mgm) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.33.3->microformer-mgm) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.33.3->microformer-mgm) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.33.3->microformer-mgm) (2025.7.14)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy->torch==2.0.1->microformer-mgm) (1.3.0)
Requirement already satisfied: optuna in /usr/local/lib/python3.11/dist-packages (5.0.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (1.19.2)
Requirement already satisfied: colorlog in /usr/local/lib/python3.11/dist-packages (from optuna) (6.12.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna) (1.24.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.41)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from optuna) (4.65.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.11/dist-packages (from alembic>=1.5.0->optuna) (4.14.1)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.3)
WARNING: Skipping jax as it is not installed.
WARNING: Skipping jaxlib as it is not installed.

In [2]:
import os
import torch
import optuna
import pandas as pd
import numpy as np

from pickle import load, dump

from sklearn.model_selection import StratifiedGroupKFold
from sklearn.metrics import roc_auc_score

from transformers import (
    GPT2ForSequenceClassification,
    Trainer,
    TrainingArguments
)

from sklearn.model_selection import train_test_split
from transformers.trainer_callback import EarlyStoppingCallback

from mgm.src.MicroCorpus import SequenceClassificationDataset

In [3]:
import zipfile

with zipfile.ZipFile('MGM_NHANES_DAPT.zip', 'r') as zip_ref:
    zip_ref.extractall('MGM_NHANES_DAPT')

In [4]:
!mgm construct \
-i asv_genus.csv \
-o corpus.pkl

Starting MGM...
No config file provided, use default config file.
No seed provided, the program will generate a random seed.
Your data will be normalized with the phylogeny mean and std. If you wish to use your own normalization, please use --no-normalize.
0 samples are dropped for all zeroes
100% 101/101 [00:00<00:00, 2168.65it/s]
Total 101 samples.
            Max length is 80.
            Average length is 66.00990099009901.
            Min length is 47.

In [5]:
from pickle import load

corpus = load(open("corpus.pkl","rb"))

corpus[0]

{'input_ids': tensor([   2, 7158, 3768, 5803,  160, 9429, 8582, 8597, 8169, 4649,  364,  242,
         8328, 3584, 3840, 5251, 1624, 1070, 1677, 1695,    9, 7858, 4831, 3013,
         2384, 8777, 4545, 8050,  486,  367, 1304,  851, 6475, 1746, 6778, 7443,
         7214,  148, 4491, 6196, 7120, 6122, 4721, 5685, 8219, 3481, 9183, 1421,
         6640, 2300, 5572, 6638, 3516, 2707, 2736, 8495, 1095, 4666,    3,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0]),
 'attention_mask': tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.])}

In [6]:
df_metadata = pd.read_csv(
    "df_metadata.csv"
)


df_metadata.head()

   Unnamed: 0          Run  disease_status  pair_id
0           0  SRR32936395               1       17
1           1  SRR32936396               0       16
2           2  SRR32936397               1        3
3           3  SRR32936398               1       16
4           4  SRR32936408               1        2

In [7]:
cv = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)


folds = list(
    cv.split(
        df_metadata,
        df_metadata["disease_status"],
        groups=df_metadata["pair_id"]
    )
)


print(len(folds))

5

In [8]:
def set_trainable_layers(
    model,
    mode
):

    for p in model.parameters():
        p.requires_grad=False


    if mode=="all":

        for p in model.parameters():
            p.requires_grad=True


    elif mode=="last2":

        for layer in model.transformer.h[-2:]:
            for p in layer.parameters():
                p.requires_grad=True


    elif mode=="last4":

        for layer in model.transformer.h[-4:]:
            for p in layer.parameters():
                p.requires_grad=True


    for p in model.score.parameters():
        p.requires_grad=True

In [9]:
def compute_metrics(eval_pred):

    logits, labels = eval_pred

    probs = torch.softmax(
        torch.tensor(logits),
        dim=1
    )[:, 1].numpy()

    auc = roc_auc_score(
        labels,
        probs
    )

    return {
        "auc": auc
    }

In [10]:
def train_fold(
    train_idx,
    val_idx,
    params,
    fold
):


    train_meta = df_metadata.iloc[train_idx]

    val_meta = df_metadata.iloc[val_idx]


    train_ids = train_meta["Run"].values
    val_ids = val_meta["Run"].values



    train_labels = (
        train_meta
        .set_index("Run")["disease_status"]
    )


    val_labels = (
        val_meta
        .set_index("Run")["disease_status"]
    )


    train_positions = [
        corpus.data.index.get_loc(x)
        for x in train_ids
    ]


    val_positions = [
        corpus.data.index.get_loc(x)
        for x in val_ids
    ]



    train_dataset = SequenceClassificationDataset(
        corpus[train_positions]["input_ids"],
        corpus[train_positions]["attention_mask"],
        torch.tensor(train_labels.values)
    )


    val_dataset = SequenceClassificationDataset(
        corpus[val_positions]["input_ids"],
        corpus[val_positions]["attention_mask"],
        torch.tensor(val_labels.values)
    )


    # cargar DAPT
    model = GPT2ForSequenceClassification.from_pretrained(
        "MGM_NHANES_DAPT",
        num_labels=2
    )


    set_trainable_layers(
        model,
        params["layers"]
    )
    args = TrainingArguments(

        output_dir=f"optuna_fold_{fold}",

        learning_rate=params["learning_rate"],

        weight_decay=params["weight_decay"],

        warmup_ratio=params["warmup_ratio"],

        num_train_epochs=20,

        per_device_train_batch_size=8,

        evaluation_strategy="epoch",

        save_strategy="epoch",

        load_best_model_at_end=True,

        metric_for_best_model="eval_auc",

        greater_is_better=True,

        logging_strategy="epoch",

        report_to="none"
    )

    trainer = Trainer(

        model=model,

        args=args,

        train_dataset=train_dataset,

        eval_dataset=val_dataset,

        compute_metrics=compute_metrics,

        callbacks=[
            EarlyStoppingCallback(
                early_stopping_patience=3
            )
        ]
    )

    trainer.train()


    preds = trainer.predict(
        val_dataset
    )


    probs = torch.softmax(
        torch.tensor(preds.predictions),
        dim=1
    )[:,1]


    auc = roc_auc_score(
        val_labels.values,
        probs.detach().numpy()
    )

    del model
    del trainer

    torch.cuda.empty_cache()

    return auc

In [11]:
def evaluate_params(params):

    aucs = []

    for fold, (train_idx, val_idx) in enumerate(folds):

        print(f"\nFold {fold+1}")

        auc = train_fold(
            train_idx=train_idx,
            val_idx=val_idx,
            params=params,
            fold=fold
        )

        print(f"AUC = {auc:.4f}")

        aucs.append(auc)

    print("\n====================")
    print("Mean AUC:", np.mean(aucs))
    print("Std AUC :", np.std(aucs))

    return aucs

In [12]:
def objective(trial):

    params = {

        "learning_rate":
        trial.suggest_float(
            "learning_rate",
            1e-5,
            5e-4,
            log=True
        ),

        "weight_decay":
        trial.suggest_categorical(
            "weight_decay",
            [0,0.01,0.1]
        ),

        "warmup_ratio":
        trial.suggest_categorical(
            "warmup_ratio",
            [0,0.1,0.2]
        ),

        "layers":
        trial.suggest_categorical(
            "layers",
            ["all","last4","last2"]
        )
    }


    try:

        scores=[]

        for fold,(train_idx,val_idx) in enumerate(folds):

            auc=train_fold(
                train_idx,
                val_idx,
                params,
                fold
            )

            scores.append(auc)


        return np.mean(scores)


    except torch.cuda.OutOfMemoryError:

        torch.cuda.empty_cache()

        return 0.0

In [13]:
study = optuna.create_study(
    direction="maximize"
)


study.optimize(
    objective,
    n_trials=30
)

'\nstudy = optuna.create_study(\n    direction="maximize"\n)\n\n\nstudy.optimize(\n    objective,\n    n_trials=30\n)\n'

In [ ]:
study.best_params

In [ ]:
pd.DataFrame(
    study.trials_dataframe()
).to_csv(
    "optuna_results.csv",
    index=False
)

In [15]:
params_last4 = {
    "learning_rate": 3.3410221978461924e-4,
    "weight_decay": 0.01,
    "warmup_ratio": 0.2,
    "layers": "last4"
}

auc_last4 = evaluate_params(params_last4)

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at MGM_NHANES_DAPT and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Fold 1

AUC = 0.7121

Fold 2

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at MGM_NHANES_DAPT and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at MGM_NHANES_DAPT and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

AUC = 0.9100

Fold 3

AUC = 0.5900

Fold 4

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at MGM_NHANES_DAPT and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at MGM_NHANES_DAPT and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

AUC = 0.7750

Fold 5

AUC = 0.5400

====================
Mean AUC: 0.7054242424242425
Std AUC : 0.13223071636643483

In [16]:
params_all = {
    "learning_rate": 4.59324400326387e-4,
    "weight_decay": 0.1,
    "warmup_ratio": 0.1,
    "layers": "all"
}

auc_all = evaluate_params(params_all)

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at MGM_NHANES_DAPT and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Fold 1

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at MGM_NHANES_DAPT and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

AUC = 0.7500

Fold 2

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at MGM_NHANES_DAPT and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

AUC = 0.8700

Fold 3

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at MGM_NHANES_DAPT and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

AUC = 0.6000

Fold 4

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at MGM_NHANES_DAPT and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

AUC = 0.7250

Fold 5

AUC = 0.5900

====================
Mean AUC: 0.7070000000000001
Std AUC : 0.10380751417888788

In [17]:
print("\nRESULTADOS")

print(f"last4: {np.mean(auc_last4):.4f} ± {np.std(auc_last4):.4f}")
print(f"all  : {np.mean(auc_all):.4f} ± {np.std(auc_all):.4f}")

RESULTADOS
last4: 0.7054 ± 0.1322
all  : 0.7070 ± 0.1038

In [18]:
# eliminar muestras de metadata que no existen en el corpus
df_final = df_metadata[
    df_metadata["Run"].isin(corpus.data.index)
].copy()


print("Muestras finales:", len(df_final))
print(df_final["disease_status"].value_counts())

Muestras finales: 101
disease_status
1    51
0    50
Name: count, dtype: int64

In [19]:
final_positions = [
    corpus.data.index.get_loc(x)
    for x in df_final["Run"]
]

In [20]:
dataset_final = SequenceClassificationDataset(

    corpus[final_positions]["input_ids"],

    corpus[final_positions]["attention_mask"],

    torch.tensor(
        df_final["disease_status"].values,
        dtype=torch.long
    )
)

In [21]:
print(len(dataset_final))
print(dataset_final[0])

101
{'input_ids': tensor([   2, 8050, 8169, 1291, 7158, 4545,  486, 9429, 7120, 3013, 8597,  160,
        1677,  364, 8777, 3768, 3584, 2300, 2384,  242, 8582, 9183, 4831,  367,
        1746, 2736, 6475, 1695, 1775, 1070, 7858, 4666, 1421, 8328, 5251, 6778,
        3481,  851, 7443, 6122, 4649, 4771,  148, 2667, 5685, 4227, 3840, 8292,
        3421, 8219, 3516, 1624, 6543, 6638, 6196, 1304, 5572,    9, 1095, 2707,
        8495, 5803, 7829,    3,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]), 'attention_mask': tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]), 'labels': tensor(1)}

In [22]:
train_idx, val_idx = train_test_split(
    np.arange(len(df_final)),
    test_size=0.20,
    stratify=df_final["disease_status"],
    random_state=42
)

df_train = df_final.iloc[train_idx].copy()
df_val = df_final.iloc[val_idx].copy()

In [23]:
print("Muestras de entrenamiento:", len(df_train))
print("Muestras de validación:", len(df_val))

print("\nDistribución entrenamiento:")
print(df_train["disease_status"].value_counts(normalize=True))

print("\nDistribución validación:")
print(df_val["disease_status"].value_counts(normalize=True))

Muestras de entrenamiento: 80
Muestras de validación: 21

Distribución entrenamiento:
disease_status
0    0.5
1    0.5
Name: proportion, dtype: float64

Distribución validación:
disease_status
1    0.52381
0    0.47619
Name: proportion, dtype: float64

In [24]:
train_positions = [
    corpus.data.index.get_loc(x)
    for x in df_train["Run"]
]

val_positions = [
    corpus.data.index.get_loc(x)
    for x in df_val["Run"]
]

In [25]:
train_dataset = SequenceClassificationDataset(
    corpus[train_positions]["input_ids"],
    corpus[train_positions]["attention_mask"],
    torch.tensor(
        df_train["disease_status"].values,
        dtype=torch.long
    )
)

In [26]:
val_dataset = SequenceClassificationDataset(
    corpus[val_positions]["input_ids"],
    corpus[val_positions]["attention_mask"],
    torch.tensor(
        df_val["disease_status"].values,
        dtype=torch.long
    )
)

In [27]:
print("Muestras de entrenamiento:", len(train_dataset))
print("Muestras de validación:", len(val_dataset))

Muestras de entrenamiento: 80
Muestras de validación: 21

In [28]:
model_final = GPT2ForSequenceClassification.from_pretrained(
    "MGM_NHANES_DAPT",
    num_labels=2
)

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at MGM_NHANES_DAPT and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [29]:
best_params = {
    "learning_rate": 4.59324400326387e-4,
    "weight_decay": 0.1,
    "warmup_ratio": 0.1
}

In [30]:
print("Learning rate:", best_params["learning_rate"])
print("Weight decay:", best_params["weight_decay"])
print("Warmup ratio:", best_params["warmup_ratio"])

Learning rate: 0.000459324400326387
Weight decay: 0.1
Warmup ratio: 0.1

In [31]:
training_args_final = TrainingArguments(
    output_dir="MGM_NHANES_finetuned_all",

    learning_rate=best_params["learning_rate"],

    weight_decay=best_params["weight_decay"],

    warmup_ratio=best_params["warmup_ratio"],

    num_train_epochs=50,

    per_device_train_batch_size=8,

    evaluation_strategy="epoch",

    save_strategy="epoch",

    load_best_model_at_end=True,

    metric_for_best_model="eval_loss",

    greater_is_better=False,

    logging_strategy="epoch",

    report_to="none"
)

In [32]:
trainer_final = Trainer(
    model=model_final,

    args=training_args_final,

    train_dataset=train_dataset,

    eval_dataset=val_dataset,

    callbacks=[
        EarlyStoppingCallback(
            early_stopping_patience=5
        )
    ]
)

In [33]:
trainer_final.train()

TrainOutput(global_step=110, training_loss=0.3748581886291504, metrics={'train_runtime': 20.4033, 'train_samples_per_second': 196.046, 'train_steps_per_second': 24.506, 'total_flos': 17082812989440.0, 'train_loss': 0.3748581886291504, 'epoch': 11.0})

In [34]:
trainer_final.save_model(
    "MGM_NHANES_finetuned_all"
)